language: go

install:
    - go get github.com/gohugoio/hugo

script:
    - hugo

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: false
    target_branch: master
    local_dir: public
    on:
        branch: source
