os: linux
language: node_js # We use Hugo Pipes, and hence need a working Node.js environment.
node_js:
  - node # Yarn needs Node.js version 4 or later.
git:
  depth: false # Hugo uses Git information to fetch .Lastmod information (enableGitInfo).
addons:
  snaps:
    - name: hugo
      channel: extended
script:
  - make build
cache:
  yarn: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  target_branch: master
  local_dir: public
  on:
    branch: source
after_deploy:
  - >
    curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache" \
    -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
    -H "Content-Type: application/json" \
    --data '{"purge_everything":true}'
env:
  global:
    - secure: qyi4dwVjk6QiZwlHw6Is5/cJkatI9rgf20dCqbuNdLhjgsoeQLW+lsgbU0gDjq4MdMC3zFWaJn1VoNFp5LfMit+mIbACHlLK7NJM2zRafRELacxYahqTuuOEwDgfoR4jQsJP5gf/gRGl0AodVsS12RuyIOra01Yc1LK9FswspcHCFE5mXwWmADkBT45HlEnPdHSanBDXHnX1HRmB09oAeUeeauNQw5ongE84KZaBXmRafVEvupd5LYqNJwgpOqHlKoC8ewfvtnYubq8dxFOLR05ftlV0pG+axLD1qKQ3bD5MR128gMwbFVH4w/kTbM1Lz4eccyAoi5XiJ5yZRYLx9B5GEwZp55Mw4Xt5tAI7UjqiiiJZX9hRG+5oA00TTsJ4kwJUgkRIcY9ZDAoej2dGhAWgdxX8sQ1qNMN2UJ09PixVzx173QxNpMKW/l6w+q1RIC6fpWjq94PL6YxHuPrUJ4x/anTKQWOJyQZIZLofL2DqDtCTkqcYjlZRORpbKTDKWnl0OeZd5hn/SCanDo/9SOQBOgjnI0vfHL98hRdD6Ear2JaWu8d/cy72uK3/46HpS4IexmFX7Z6z7zALp5uGBjiUD+HH1/jzgSR2B00rTtqPj7Y0XNkg76nvFYsdr0echw12gdUdMb0O2yK7iDYLRlXHPGDyp67ZxCzquveVt/4=
    - secure: jmjt0iax57gji2+TKQBt18hUGJE/1bkrQ5VZZW6/mhhktY04yxbudexeRbGj2QxA0aID7gvARSHZQccLSmZ0cQqKps30Lx+7ExPQwHLpk142kiJChz6s3QQGFtoJZ0VqVeTKnJfnJiPdDQPByBKEIyHluiOyGB2aFVyldjIYsEdWiFjF3/0yVbbEVlfMqoix1ImLRB+UO7ZBCsrx77OwL/KyjlxL8zKsrNJ6LKEFSa5uZLzMhsARa02QwqWH/1HS3eV4Go9IDEP7zponiU9ZjZjahqZLwtaKp0yPYcPC1mij6rYJK+BekJCbgIoSNMCtSonXqYR7kAQz9Rnahh3OK96Hu9M5AbHDKgg2o+wvbdggc5NjRl0sUKwD1uwDQfAPbHay35cKuafW7VB4wXyd4fZdV0ZPIeyHn1Ys5lCE/l8HeQQ2dFkRYVrUrxB2WWJ/zrRaV6pnud9wAxasy3FO9bZqVUrM/NfS3lVJbxJfOJxpJL+1RluOPLAn9R81kfBjaThN67sO6SMT1XsCiqfg9oVuIZrQIVzpDOr6K55lByCXDu3VEccJZm1BjJOgOiY/BltRey4NHrWqd2tvNQn/hOx8pGTafyHZWlFUeQSsXrFqUfZAfFZ4Pi6Xo9nuTJTezzMlMkmF9TVY4P4r0v8KaaX3yZRz837yiN9nFsn8sSE=
    - secure: OnM3pRboUBGeUYYaOXbOD2X/2hhyfEhssVy9IMLng5eEhrqmsBMQ51FYc5xbqEVHsLhFrrbH2FlD0ZKRi2aq/c5zdnMwMeKUtQRk2jZnmdeu7lSn8Hgeci+9nA7dLXpYmyCVB90Apta6vE8n9Iw2NmTa9/UefL3YfBzA45b/l7IwVSFSTNKRe3+AxRvlTru04ZFyy1t/wU4iPBAT9wxCaPjAydRznYxtRAWl4P/7vxnwCzFl7ey5UC9BB9S0cxDIpswSn+48jJpi2d5GMhtlx3p23OO/832fk2mgjGal6ITlij0g7N6+1ucH35Fy4B2geQuRKyIXKoksgu4pkBhiG6S1SC1BU/+ddcctBoDpZ4Id6WK4jzyri4eVcNz0+yIzQFRoYciX1B60dOAFB8OJ/pjiy4hvIUBT6BZnouWUySevUNEgprx1WzU5RieViFsZ1KehU3xbI5r//LBCcPnjwSV/hPTPx0k8pZQ5YBvefi/w8kzhezHaC/Cc69R33olfwr0dRvq+3Urlho11lC3wDf88Oj0daWT7IocNf+BxXOBWJfZ6vAtEs+GQx21000ivW38Fewa+8e0ei8Fwo30tybw8EjH139LS4gAS24dZK8iD4V5goDJ14qI9LKhyQTYw1BgIEgtRydH6+Uu710T2dDVZBNUTbn7jlnwTDFWOeqA=
