baseURL = "https://eiken.dev/"
languageCode = "en-us"
title = "eikendev"
footnoteReturnLinkContents = "↩"
rssLimit = 20
disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = true # Fetch .Lastmod from Git repository.
pluralizelisttitles = false
pygmentsUseClasses=true

[taxonomies]
	tag = "tags"

[params]
	title = "eikendev"
	author = "Raphael Eikenberg (eikendev)"
	description = "Coding projects and blog posts by eikendev. Always happy to learn something new. Also interested in infosec? Join my journey!"
	keywords = "coding, programming, projects, infosec, information security, system security, portfolio"
	images = ["/img/logo.png"]
	github = "eikendev"
	gitlab = "eikendev"
	twitter = "eikendev"

# https://gohugo.io/templates/rss/
[author]
	name = "eikendev"
	email = "hello@eiken.dev"

[permalinks]
	blog = "blog/:year/:month/:title/"

# https://gohugo.io/templates/sitemap-template/
[sitemap]
	changefreq = "weekly"
	filename = "sitemap.xml"
	priority = 0.5

# https://gohugo.io/getting-started/configuration-markup
# https://xyproto.github.io/splash/docs/all.html
[markup]
	[markup.highlight]
		lineNos = true
		lineNumbersInTable = true
		tabWidth = 4
    [markup.goldmark.extensions]
        footnote = true
        strikethrough = true
        table = true
        taskList = true
        typographer = true
