#!/usr/bin/env bash

DIRECTORY='./public'

find_urls () {
	lynx -dump -listonly -hiddenlinks=merge -nonumbers "$1" \
		| grep -i 'https\?://.*'
}

export -f find_urls

find "$DIRECTORY" -type f -name '*.html' -print0 \
	| xargs --max-procs=4 --max-args=1 --null bash -c 'find_urls "$@"' _ \
	| sort \
	| uniq -u \
	| grep -v 'https://news.ycombinator.com/submitlink?' \
	| grep -v 'https://twitter.com/intent/tweet?' \
	| grep -v 'https://www.reddit.com/submit?'
