name: Main
on:
  push:
    branches:
      - source
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Hugo uses Git information to fetch .Lastmod information (enableGitInfo).
      - name: Build
        run: make build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./public
  purge_cache:
    name: Purge cache
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
  broken_links:
    name: Check for broken links
    runs-on: ubuntu-latest
    needs: purge_cache
    steps:
      - name: Check for broken links
        uses: elliotforbes/broken-link-checker@1.0.2
        with:
          url: 'https://eiken.dev/'
